// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfPacketEvent struct {
	_         structs.HostLayout
	SrcIp     uint32
	DestIp    uint32
	PktSize   uint16
	Protocol  uint8
	Ttl       uint8
	Tos       uint8
	IpHdrLen  uint8
	IpId      uint16
	IpFragOff uint16
	SrcPort   uint16
	DestPort  uint16
	_         [2]byte
	TcpSeq    uint32
	TcpAck    uint32
	TcpFlags  uint8
	TcpHdrLen uint8
	TcpWindow uint16
	Direction uint8
	Pad       [3]uint8
	Timestamp uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapPacketEvents   = "packet_events"
	bpfMapPortConfig     = "port_config"
	bpfProgHandleEgress  = "handle_egress"
	bpfProgHandleIngress = "handle_ingress"
	bpfVarUnusedEvent    = "unused_event"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleEgress  *ebpf.ProgramSpec `ebpf:"handle_egress"`
	HandleIngress *ebpf.ProgramSpec `ebpf:"handle_ingress"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	PacketEvents *ebpf.MapSpec `ebpf:"packet_events"`
	PortConfig   *ebpf.MapSpec `ebpf:"port_config"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	PacketEvents *ebpf.Map `ebpf:"packet_events"`
	PortConfig   *ebpf.Map `ebpf:"port_config"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.PacketEvents,
		m.PortConfig,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleEgress  *ebpf.Program `ebpf:"handle_egress"`
	HandleIngress *ebpf.Program `ebpf:"handle_ingress"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleEgress,
		p.HandleIngress,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
