apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-redis
  namespace: devops-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-redis
  template:
    metadata:
      labels:
        app: devops-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: devops-redis-service
  namespace: devops-system
spec:
  selector:
    app: devops-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
